apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-access-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: newwork1-sa@newwork1.iam.gserviceaccount.com

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: secret-access-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: secret-access-role-bind
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-access-role
subjects:
- kind: ServiceAccount
  name: secret-access-sa
  namespace: default

---

apiVersion: v1
kind: Pod
metadata:
  name: py
  namespace: default
spec:
  serviceAccountName: secret-access-sa
  containers:
  - image: gcr.io/newwork1/py:v2
    name: py
